Lab03-Lab06 - Copy/Lab03/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab03.Models;
using Lab03.Models.ViewModels;

namespace Lab03.Controllers {
    public class CityController : Controller {
        private iCityRepo cityRepo;
        private iContinentRepo contRepo;
        private iCityProductRepo cityProductRepo;
        private iProductRepo productRepo;
        private int PageSize = 3;
        public CityController(iCityRepo cityr, iContinentRepo contr, iCityProductRepo cpr, iProductRepo pr) {
            cityRepo = cityr; contRepo = contr; cityProductRepo = cpr; productRepo = pr;
        }
        [Route("/City/CityDetails", Name = "viewCity")]
        public ViewResult ViewCity(int CityId, int importsPageNumber = 1, int exportsPageNumber = 1, int producesPageNumber = 1) {
            City city = cityRepo.Cities.FirstOrDefault(p => p.CityId == CityId);            
            CityProduct[] cityProducts = cityProductRepo.CityProducts.ToArray();
            Product[] products = productRepo.Products.ToArray();
            List<City.ProductInfo> simpleImports = new List<City.ProductInfo>();
            List<City.ProductInfo> simpleExports = new List<City.ProductInfo>();
            List<City.ProductInfo> simpleProduce = new List<City.ProductInfo>();
            CityProduct[] productsOfThisCity = new CityProduct[productRepo.Products.Count()];
            int i = 0;
            for(int j = 0; j < cityProducts.Length; j++) {
                if(cityProducts[j].CityId == city.CityId) {
                    productsOfThisCity[i] = cityProducts[i++];
                    for(int k = 0; k < products.Length; k++) {
                        if(cityProducts[j].ProductId == products[k].productId) {
                            if(cityProducts[j].Type == 2 || cityProducts[j].Type == 4 ||
                                cityProducts[j].Type == 5 || cityProducts[j].Type == 6) {
                                City.ProductInfo pI = new City.ProductInfo(
                                    cityProducts[j].ProductId, products[k].productName, cityProducts[j].PerUnitLocalValue, cityProducts[j].PerUnitProductionPrice,
                                    cityProducts[j].ScheduledAnnualUnitProduction, cityProducts[j].MaximumPotentialUnitProduction
                                );
                                simpleImports.Add(pI);
                            } 
                            if(cityProducts[j].Type == 3 || cityProducts[j].Type == 4 ||
                                cityProducts[j].Type == 6 || cityProducts[j].Type == 7) {
                                City.ProductInfo pI = new City.ProductInfo(
                                    cityProducts[j].ProductId, products[k].productName, cityProducts[j].PerUnitLocalValue, cityProducts[j].PerUnitProductionPrice,
                                    cityProducts[j].ScheduledAnnualUnitProduction, cityProducts[j].MaximumPotentialUnitProduction
                                );
                                simpleExports.Add(pI);
                            }
                            if(cityProducts[j].Type == 1 || cityProducts[j].Type == 2 ||
                                cityProducts[j].Type == 3 || cityProducts[j].Type == 4) {
                                City.ProductInfo pI = new City.ProductInfo(
                                    cityProducts[j].ProductId, products[k].productName, cityProducts[j].PerUnitLocalValue, cityProducts[j].PerUnitProductionPrice,
                                    cityProducts[j].ScheduledAnnualUnitProduction, cityProducts[j].MaximumPotentialUnitProduction
                                );
                                simpleProduce.Add(pI);
                            }
                            break;
                        }
                    }
                }
            }
            city.ContinentName = contRepo.Continents.First(c => c.ContinentId == city.ContinentId).Name;
            city.ProductsImported2 = simpleImports.ToArray();
            city.ProductsExported2 = simpleExports.ToArray();
            city.ProductsProduced2 = simpleProduce.ToArray();
            PagingInfo importsPages = new PagingInfo() {
                CurrentPage = importsPageNumber,
                ItemsPerPage = PageSize,
                TotalItems = city.ProductsImported2.Length
            };
            PagingInfo exportsPages = new PagingInfo() {
                CurrentPage = exportsPageNumber,
                ItemsPerPage = PageSize,
                TotalItems = city.ProductsExported2.Length
            };
            PagingInfo producesPages = new PagingInfo() {
                CurrentPage = producesPageNumber,
                ItemsPerPage = PageSize,
                TotalItems = city.ProductsProduced2.Length
            };
            CityViewModel cvm = new CityViewModel {
                City = city, ImportsPages = importsPages, ExportsPages = exportsPages, ProducesPages=producesPages, CityProducts = productsOfThisCity
            };
            return View("CityDetails", cvm);            
        }
    }
}

Lab03-Lab06 - Copy/Lab03/Views/Shared/_CityPanel.cshtml
<div id="cityPanel" style="display:block; color:white;">
</div>

Lab03-Lab06 - Copy/Lab03/Views/Shared/_CityProductEditor.cshtml
@model CityProduct
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-action="UpdateCityProduct" method="post">
    <div class="form-group">
        <label>Product Name:</label>
        <input asp-for="Product.productName" class="form-control" disabled="disabled" />
    </div>
    <div class="hidden">
        <input asp-for="ProductId" class="hidden" />
    </div>
    <div class="hidden">
        <input asp-for="CityId" class="hidden" />
    </div>
    <div class="form-group">
        <label>Current Surplus in this City:</label>
        <input asp-for="CurrentSurplus" class="form-control" />
    </div>
    <div class="form-group">
        <label>Maximum Annual Production Rate:</label>
        <input asp-for="MaximumPotentialUnitProduction" class="form-control" />
    </div>
    <div class="form-group">
        <label>Scheduled Annual Production:</label>
        <input asp-for="ScheduledAnnualUnitProduction" class="form-control" />
    </div>
    <div class="form-group">
        <label>Import/Export/Production Code:</label>
        <input asp-for="Type" class="form-control" />
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="UPDATE THIS CITY-PRODUCT"/>
    </div>
</form>

Lab03-Lab06 - Copy/Lab03/Views/Shared/_WorldEconomyPanel.cshtml
@model IndexViewModel
<div id="worldEconomyPanel">
    <p id="wEPTitle">World Market Value: $@ViewBag.WorldMarketValue B</p>
    @foreach (City c in Model.Cities){
        <div class="section @if(c.Coordinate4 <.64){@("Southern")} }">        
            <a asp-route="viewCity" asp-route-CityId="@c.CityId">@c.Name</a>
            <!--Html.ActionLink(c.Name, "ViewCity", "City", new{city = c})-->
            <p>GDP: @c.GDP</p>
        </div>
    }
</div>

<button type="button" id="funnyButton" style="top:30px; left:5px; position:fixed;" onclick="funnyButton();">
    View
    <select type="select" id="funnySelector">
        <option type="option" value="All">All Cities</option>
        <option type="option" value="Northern">Cities North of the Equator</option>
        <option type="option" value="Southern">Cities South of the Equator</option>
    </select>
</button>

<script>
    function funnyButton() {
        var fs = document.getElementById("funnySelector");
        var sec = document.querySelectorAll(".section");
        var listHeader = document.getElementById("wEPTitle");
        //alert(document.getElementById("funnySelector").value);
        if (fs.value == "All") {
            listHeader.innerHTML = "World Market Value: $@ViewBag.WorldMarketValue B";
            sec.forEach(function (s) {
                s.style.display = "block";
            });
        } else if (fs.value == "Northern") {
            listHeader.innerHTML = "Northern Market Value: $@ViewBag.NorthernGDP B";
            sec.forEach(function (s) {
                if (s.classList.contains("Southern"))
                    s.style.display = "none";
                else s.style.display = "block";
            });
        } else {
            listHeader.innerHTML = "Southern Market Value: $@ViewBag.SouthernGDP B";
            sec.forEach(function (s) {
                if (s.classList.contains("Southern"))
                    s.style.display = "block";
                else s.style.display = "none";
            });
        }
    }
    document.getElementById("funnySelector").onmouseenter = function () {
        document.getElementById("funnyButton").onclick = null;
    }
    document.getElementById("funnySelector").onmouseleave = function () {
        document.getElementById("funnyButton").onclick = funnyButton;
    }
    document.getElementById("worldEconomyPanel").onmouseenter = function () {
        mouseOffofMap = true;
    }
    document.getElementById("worldEconomyPanel").onmouseleave = function () {
        mouseOffofMap = false;
    }
</script>